version: '3'
services:
  my-postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data-access-object
    ports:
      - 5432:5432
    restart: always



